sonar.projectKey=Jean-Killian_quiz-ai-education
sonar.organization=jean-killian

# Sources
sonar.sources=app,resources,routes,config,database
sonar.exclusions=vendor/**,node_modules/**,storage/framework/views/**,public/**,tests/**

# Encoding
sonar.sourceEncoding=UTF-8
