sonar.projectKey=Jean-Killian_quiz-ai-education
sonar.organization=jean-killian

# Sources
sonar.sources=app,resources,routes,config,database
sonar.exclusions=vendor/**,node_modules/**,storage/framework/views/**,public/**,tests/**

# Tests
sonar.tests=tests
sonar.php.tests.reportPath=build/logs/phpunit.xml
sonar.php.coverage.reportPaths=build/logs/clover.xml

# Encoding
sonar.sourceEncoding=UTF-8
