name: CI/CD Quality Gate

on:
  push:
    branches: [ "main", "review/*", "feat/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, sqlite, pdo_sqlite
        coverage: none

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Setup Environment
      run: |
        cp .env.exemple .env
        php artisan key:generate
        touch database/database.sqlite
        php artisan config:clear

    - name: Execute Tests
      run: vendor/bin/phpunit

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
