name: CI/CD Quality Gate

on:
  push:
    branches: [ "main", "review/*", "feat/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, sqlite3
        coverage: xdebug

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Setup Environment
      run: |
        cp .env.exemple .env
        php artisan key:generate
        touch database/database.sqlite

    - name: Install NPM & Build
      run: |
        npm install
        npm run prod

    - name: Execute Tests
      run: php artisan test

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
